#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'

require 'poodr_rpg'

program_config = {}

opts = OptionParser.new
opts.on('-h', '--help') { program_config[:h] = true }
opts.parse!(ARGV)

if program_config[:h]
  puts 'Help me!'
else
  PoodrRpg::Battle.new.run
end
